\section{Debugging information}
<<print-debug-info, eval=DEBUG, echo=FALSE>>=
message(sprintf("Command line: %s", paste(argv, collapse = " ")))
message(sprintf("  path.input:        %s", path.input))
message(sprintf("  path.tp:           %s", path.tp))
message(sprintf("  path.fp:           %s", path.fp))
message(sprintf("  path.fn:           %s", path.fn))
message(sprintf("  genome:            %s", genome))
message(sprintf("  path.gold_regions: %s", path.gold_regions))
message(sprintf("  path.call_regions: %s", path.call_regions))
message(sprintf("  DEBUG:             %s", DEBUG))
sessionInfo()
@
