\section{Debugging information}
<<print-debug-info, eval=DEBUG, echo=FALSE>>=
message(sprintf("Command line: %s", paste(argv, collapse = " ")))
message(sprintf("  DEBUG:             %s", DEBUG))
message(sprintf("  DEBUG.chrom:       %s", DEBUG.chrom))
message(sprintf("  path.tp:           %s", path.tp))
message(sprintf("  path.fp:           %s", path.fp))
message(sprintf("  path.fn:           %s", path.fn))
message(sprintf("  path.gold:         %s", path.gold))
message(sprintf("  genome:            %s", genome))
message(sprintf("  path.gold_regions: %s", path.gold_regions))
message(sprintf("  path.function_regions_prefix: %s", path.function_regions_prefix))
message(sprintf("  path.mask_regions_prefix:     %s", path.mask_regions_prefix))
sessionInfo()
@

